package com.builtbroken.atomic.config;

import com.builtbroken.atomic.AtomicScience;
import com.builtbroken.atomic.proxy.ContentProxy;
import net.minecraftforge.common.config.Configuration;

import java.io.File;

/**
 * @see <a href="https://github.com/BuiltBrokenModding/VoltzEngine/blob/development/license.md">License</a> for what you can and can't do with the code.
 * Created by Dark(DarkGuardsman, Robert) on 5/27/2018.
 */
public class ConfigThermal extends ContentProxy
{
    //To boil 1 block of water takes 1,562,379.05 KJ
    /** Heat output from fuel rod when active in a reactor */
    public static int HEAT_REACTOR_FUEL_ROD = 1562379 * 20;

    /** Heat output from fuel rod when active in a reactor */
    public static int HEAT_REACTOR_BREEDER_ROD = 1562379 * 10;

    public ConfigThermal()
    {
        super("config.thermal");
    }

    @Override
    public void preInit()
    {
        Configuration configuration = new Configuration(new File(AtomicScience.configFolder, "Thermal.cfg"), AtomicScience.VERSION);
        configuration.load();
        reactorItems(configuration);
        configuration.save();
    }

    private void reactorItems(Configuration configuration)
    {
        final String cat_reactor = "reactor_heat";
        configuration.addCustomCategoryComment(cat_reactor, "Heat generated by an item when installed in a reactor. " +
                "Heat values are scaled by the reactor & environment in use. This value is used as a starter value for the reactor & item. " +
                "It will be calculated over time, estimated to match the area, and then spread over the environment. Try to keep the values low" +
                "as the system is limited by Integer.MAX (~2.7B). Setting it too high will break the system.");

        HEAT_REACTOR_FUEL_ROD = configuration.getInt("fuel_rod", cat_reactor, HEAT_REACTOR_FUEL_ROD, 1, Integer.MAX_VALUE / 2,
                "Heat generated by the fuel rod");

        HEAT_REACTOR_BREEDER_ROD = configuration.getInt("breeder_rod", cat_reactor, HEAT_REACTOR_BREEDER_ROD, 1, Integer.MAX_VALUE / 2,
                "Heat generated by the breeder fuel rod");
    }
}
